GET http://localhost:3000/places?text=rua julio coutinho, itajai, 25

###
@originId = ChIJESIhdg3M2JQRueehjMdUznA
@destinationId = ChIJSYUCG_HL2JQRoWYhwUbI1F0
###
GET http://localhost:3000/directions?originId={{ originId }}&destinationId={{ destinationId }}